<a href="https://colab.research.google.com/github/jaymalak/Capstone1/blob/master/Capstone_Project_I__v3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Installation / Import of packages





In [4]:
!pip install mysql.connector

Processing /root/.cache/pip/wheels/8c/83/a1/f8b6d4bb1bd6208bbde1608bbfa7557504bed9eaf2ecf8c175/mysql_connector-2.2.9-cp36-cp36m-linux_x86_64.whl


In [205]:
!pip install plotly

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.pyplot import pie, axis, show
%matplotlib 


Using matplotlib backend: agg


In [206]:
# Making plotly specific imports
# These imports are necessary to use plotly offline without signing in to their website.

from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objs as go
import chart_studio.plotly as py
from plotly import tools
init_notebook_mode(connected=True)

In [0]:
import plotly

In [0]:
pd.set_option('float_format', '{:3f}'.format)
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

##Data Fetched for MYSQL and CSV

In [0]:
from mysql.connector import Error

In [0]:
import mysql.connector

In [10]:
try:
   connection = mysql.connector.connect(host='cpanel.insaid.co', database='Capstone1', user='student',password='student')

   if connection.is_connected():
     db_info = connection.get_server_info()
     print("connected to MySQ Server version", db_info)
     sql_gender_age = "select * from gender_age_train"
     sql_ph_brand = "select * from phone_brand_device_model"
    
     cursor = connection.cursor()
     cursor.execute(sql_gender_age)
     record = cursor.fetchall()
     gender_age_train = pd.DataFrame(record)
     
     cursor.execute(sql_ph_brand)
     record1 = cursor.fetchall()
     phone_brand = pd.DataFrame(record1)

 
except Error as e :
  print ("Error while connecting  to MySQL", e)

finally :
  if (connection.is_connected()) :
    cursor.close()
    connection.close()
    print("MySQL connection is closed")

connected to MySQ Server version 5.6.46-cll-lve
MySQL connection is closed


In [11]:
connection

In [12]:
!pip install googletrans

  Created wheel for googletrans: filename=googletrans-2.4.0-cp36-none-any.whl size=15777 sha256=d048d4b3a88674e96b6647f2578af553b0a11c771ed382fd307f3b25643f848f
  Stored in directory: /root/.cache/pip/wheels/50/d6/e7/a8efd5f2427d5eb258070048718fa56ee5ac57fd6f53505f95
Successfully built googletrans


In [0]:
gender_age_train.head()

In [0]:
phone_brand.head()

In [0]:
gender_age_train.info()

In [0]:
phone_brand.info()

In [13]:
gender_age_train.shape

(74645, 4)

In [14]:
phone_brand.shape

(87726, 3)

In [0]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [0]:
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [17]:
link = 'https://drive.google.com/open?id=1ggM3ZXElSob6ZSzWaiNNT3SgiNDHGv6d' # The shareable link
fluff, id = link.split('=')
print (id) # Verify that you have everything after '='

1ggM3ZXElSob6ZSzWaiNNT3SgiNDHGv6d


In [0]:
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('events.csv')  
events = pd.read_csv('events.csv')

In [19]:
events.head()

event_id                device_id  ...   city  state
0     1.000000 29182687948017176.000000  ...  Delhi  Delhi
1  7104.000000 29182687948017176.000000  ...  Delhi  Delhi
2 29661.000000 29182687948017176.000000  ...  Delhi  Delhi
3 33133.000000 29182687948017176.000000  ...  Delhi  Delhi
4 38980.000000 29182687948017176.000000  ...  Delhi  Delhi

[5 rows x 7 columns]

In [20]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3252950 entries, 0 to 3252949
Data columns (total 7 columns):
event_id     float64
device_id    float64
timestamp    object
longitude    float64
latitude     float64
city         object
state        object
dtypes: float64(4), object(3)
memory usage: 173.7+ MB


In [21]:
events.head()

event_id                device_id  ...   city  state
0     1.000000 29182687948017176.000000  ...  Delhi  Delhi
1  7104.000000 29182687948017176.000000  ...  Delhi  Delhi
2 29661.000000 29182687948017176.000000  ...  Delhi  Delhi
3 33133.000000 29182687948017176.000000  ...  Delhi  Delhi
4 38980.000000 29182687948017176.000000  ...  Delhi  Delhi

[5 rows x 7 columns]

In [22]:
events.groupby(['device_id','city'])['device_id'].count().sort_values(ascending=False)

device_id                    city          
5536513450525271040.000000   Chennai           33426
-4792366453774469120.000000  Chennai           14568
442842061129641600.000000    Pune               6731
-6242501228649113600.000000  Delhi              4150
-8340098378141155328.000000  Delhi              3973
                                               ...  
-1570707258379526912.000000  Bikaner               1
-1572798778011001600.000000  Chilakalurupet        1
-1574234168805029120.000000  Chennai               1
-1578603494878530048.000000  UranIslampur          1
5372858667551875072.000000   Mirat                 1
Name: device_id, Length: 60865, dtype: int64

In [23]:
events.groupby('state')['event_id'].count().sort_values(ascending=False)

state
Delhi                       751733
Maharashtra                 677105
TamilNadu                   436282
AndhraPradesh               321332
MadhyaPradesh               232690
Rajasthan                   196361
WestBengal                  196161
Karnataka                    99058
UttarPradesh                 94750
Gujarat                      42881
Bihar                        35472
Punjab                       26195
Kerala                       23148
Haryana                      21053
Jharkhand                    18060
Orissa                       15904
Telangana                    12784
Assam                        12021
Chhattisgarh                  9754
Uttaranchal                   7720
JammuandKashmir               5385
Goa                           3250
Nagaland                      2298
Pondicherry                   1741
Mizoram                       1613
AndamanandNicobarIslands      1515
Meghalaya                     1515
HimachalPradesh               1409
Manipur       

In [24]:
events.groupby(['state','city'])['event_id'].count().sort_values(ascending=False)

state          city            
Delhi          Delhi               744212
TamilNadu      Chennai             366828
Maharashtra    Pune                317213
               Mumbai              285246
AndhraPradesh  Visakhapatnam       235725
                                    ...  
               Ramachandrapuram       279
Punjab         Sirhind                269
AndhraPradesh  Tadepallegudem         264
Orissa         Brajrajnagar           263
TamilNadu      Kovilpatti             258
Name: event_id, Length: 943, dtype: int64

In [0]:
gender_age_train.columns=['device_id','gender','age','age_group']

In [26]:
gender_age_train.head()

device_id gender  age age_group
0 -8076087639492063270      M   35    M32-38
1 -2897161552818060146      M   35    M32-38
2 -8260683887967679142      M   35    M32-38
3 -4938849341048082022      M   30    M29-31
4   245133531816851882      M   30    M29-31

In [27]:
gender_age_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74645 entries, 0 to 74644
Data columns (total 4 columns):
device_id    74645 non-null int64
gender       74645 non-null object
age          74645 non-null int64
age_group    74645 non-null object
dtypes: int64(2), object(2)
memory usage: 2.3+ MB


In [0]:
phone_brand.columns=['device_id','brand','model']

In [29]:
phone_brand.head()

device_id brand    model
0  1877775838486905855  vivo      Y13
1 -3766087376657242966    小米     V183
2 -6238937574958215831  OPPO      R7s
3  8973197758510677470    三星    A368t
4 -2015528097870762664    小米  红米Note2

In [30]:
phone_brand.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87726 entries, 0 to 87725
Data columns (total 3 columns):
device_id    87726 non-null int64
brand        87726 non-null object
model        87726 non-null object
dtypes: int64(1), object(2)
memory usage: 2.0+ MB


In [31]:
gender_age_train.groupby(by='age_group')

In [32]:
#missing data in gender_age_train
total = gender_age_train.isnull().sum().sort_values(ascending=False)
percent = (gender_age_train.isnull().sum()/gender_age_train.isnull().count()).sort_values(ascending=False)
missing_data_genderage = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data_genderage.head(20)
print(missing_data_genderage)


           Total  Percent
age_group      0 0.000000
age            0 0.000000
gender         0 0.000000
device_id      0 0.000000


In [33]:
##missing data in phone_brand
total = phone_brand.isnull().sum().sort_values(ascending=False)
percent = (phone_brand.isnull().sum()/phone_brand.isnull().count()).sort_values(ascending=False)
missing_data_phoneband = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data_phoneband.head(20)
print(missing_data_phoneband)


           Total  Percent
model          0 0.000000
brand          0 0.000000
device_id      0 0.000000


In [34]:
##missing data in events
total = events.isnull().sum().sort_values(ascending=False)
percent = (events.isnull().sum()/events.isnull().count()).sort_values(ascending=False)
missing_data_events = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data_events.head(20)
print(missing_data_events)

           Total  Percent
device_id    453 0.000139
latitude     423 0.000130
longitude    423 0.000130
state        377 0.000116
city           0 0.000000
timestamp      0 0.000000
event_id       0 0.000000


Observation - In events 377 values are missing. But city are not missing. So we can update state basis of city
  

## PANDAS PROFILING BEFORE DATA PROCESSING

In [35]:
!pip install pandas_profiling

In [36]:
import pandas_profiling                                                      # Get a quick overview for all the variables using pandas_profiling                                         
profileevents = pandas_profiling.ProfileReport(events)
profileevents.to_file("eventbeforeprocess.html")


/usr/local/lib/python3.6/dist-packages/pandas_profiling/describe.py:392: FutureWarning:

The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.



In [37]:
pandas_profiling.ProfileReport(events)

/usr/local/lib/python3.6/dist-packages/pandas_profiling/describe.py:392: FutureWarning:

The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.



In [0]:
from google.colab import files
files.download("eventbeforeprocess.html")

### DataProcessing for records where Device Ids are NULL

In [38]:
# creating bool series True for NaN values  
bool_dev = pd.isnull(events["device_id"])  

events[bool_dev]

event_id  device_id  ...     city    state
23808     72957.000000        nan  ...    Delhi    Delhi
23820     78897.000000        nan  ...    Delhi    Delhi
23831     94768.000000        nan  ...    Delhi    Delhi
23852    127677.000000        nan  ...    Delhi    Delhi
24093    442470.000000        nan  ...    Delhi    Delhi
...                ...        ...  ...      ...      ...
3098746 1882296.000000        nan  ...  Bardoli  Gujarat
3098757 1952481.000000        nan  ...  Bardoli  Gujarat
3098801 2235564.000000        nan  ...  Bardoli  Gujarat
3098833 2452592.000000        nan  ...  Bardoli  Gujarat
3098901 3050759.000000        nan  ...  Bardoli  Gujarat

[453 rows x 7 columns]

In [168]:
events[bool_dev].groupby(['state','city']).count()

event_id  device_id  ...  longitude  latitude
state         city                                ...                     
AndhraPradesh Visakhapatnam        69          0  ...         69        69
Delhi         Delhi                69          0  ...         69        69
Gujarat       Bardoli              16          0  ...         16        16
              Jetpur               16          0  ...         16        16
MadhyaPradesh Indore               51          0  ...         51        51
Maharashtra   Pune                 72          0  ...         72        72
Punjab        Hoshiarpur           16          0  ...         16        16
Rajasthan     Jaipur               81          0  ...         81        81
TamilNadu     Chennai              63          0  ...         63        63

[9 rows x 5 columns]

In [194]:
dev = events[(events['city'] == "Chennai") & (events['device_id'].isnull())] 
dev.head()

event_id  device_id  ...     city      state
1585123  58816.000000        nan  ...  Chennai  TamilNadu
1585135  62553.000000        nan  ...  Chennai  TamilNadu
1585167  97365.000000        nan  ...  Chennai  TamilNadu
1585408 315532.000000        nan  ...  Chennai  TamilNadu
1585599 477494.000000        nan  ...  Chennai  TamilNadu

[5 rows x 7 columns]

In [196]:
##events.query('longitude == 83.357991 and latitude == 17.805195',engine='python') ##6844192269280791552.000000
##events.query('longitude == 77.303153 and latitude == 28.728888',engine='python') ##not found
##events.query('longitude == 73.169345 and latitude == 21.194283',engine='python') ##not found
##events.query('longitude == 70.686387	 and latitude == 21.790693	',engine='python') ##1688015122502424064.000000
##events.query('longitude == 75.882956	 and latitude == 22.814519	',engine='python') ##not found
##events.query('longitude == 73.862756	 and latitude == 18.628057	',engine='python') ##not found
##events.query('longitude == 75.992551	 and latitude == 31.561747',engine='python') ##not found
events.query('longitude == 75.846007	 and latitude == 26.960796',engine='python') ##not found
##events.query('longitude == 80.309272	 and latitude == 13.149176',engine='python') ##7662139143719919616.000000




Empty DataFrame
Columns: [event_id, device_id, timestamp, longitude, latitude, city, state]
Index: []

###Observations 
  453 device Ids are blank. But there is no link on the basis of which we can update device ID. So it will be better that we drop the data with Null device IDs. 
  or  we can update device ids with maximum count device in the same city. but we found device numbers for 3 cities only.

### Data Processing for records where LAT -LONG are NULL

In [67]:
# creating bool series True for NaN values  
bool_long = pd.isnull(events["longitude"])  
##bool_lat = pd.isnull(events["latitude"])  

events[bool_long]

event_id                  device_id  ...    city  state
78116     53343.000000 4782582047729166336.000000  ...   Delhi  Delhi
78331    295454.000000 4782582047729166336.000000  ...   Delhi  Delhi
78597    594751.000000 4782582047729166336.000000  ...   Delhi  Delhi
78848    892922.000000 4782582047729166336.000000  ...   Delhi  Delhi
79022   1081858.000000 4782582047729166336.000000  ...   Delhi  Delhi
...                ...                        ...  ...     ...    ...
3025458 3014889.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025460 3024797.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025483 3123229.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025508 3212639.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025513 3219204.000000 3099168546198768640.000000  ...  Bagaha  Bihar

[423 rows x 7 columns]

### Observations 
423 record have longitude and latitude are having null values. 
Same can be update on the basis of city's common lat -longs

In [68]:
events[bool_long].groupby(['state','city']).count()

event_id  device_id  ...  longitude  latitude
state         city                                ...                     
AndhraPradesh Visakhapatnam        63         63  ...          0         0
Bihar         Araria               14         14  ...          0         0
              Bagaha               14         14  ...          0         0
Delhi         Delhi                63         63  ...          0         0
MadhyaPradesh Indore               63         63  ...          0         0
Maharashtra   Pune                 63         63  ...          0         0
Punjab        Moga                 14         14  ...          0         0
Rajasthan     Jaipur               66         66  ...          0         0
TamilNadu     Chennai              63         63  ...          0         0

[9 rows x 5 columns]

In [69]:
lat_long = pd.merge(events[bool_long],events,how='inner', left_on='device_id', right_on='device_id')
lat_long.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 736795 entries, 0 to 736794
Data columns (total 13 columns):
event_id_x     736795 non-null float64
device_id      736795 non-null float64
timestamp_x    736795 non-null object
longitude_x    0 non-null float64
latitude_x     0 non-null float64
city_x         736795 non-null object
state_x        736795 non-null object
event_id_y     736795 non-null float64
timestamp_y    736795 non-null object
longitude_y    728140 non-null float64
latitude_y     728140 non-null float64
city_y         736795 non-null object
state_y        736795 non-null object
dtypes: float64(7), object(6)
memory usage: 78.7+ MB


In [70]:
lat_long.head()

event_id_x                  device_id  ... city_y  state_y
0 53343.000000 4782582047729166336.000000  ...  Delhi    Delhi
1 53343.000000 4782582047729166336.000000  ...  Delhi    Delhi
2 53343.000000 4782582047729166336.000000  ...  Delhi    Delhi
3 53343.000000 4782582047729166336.000000  ...  Delhi    Delhi
4 53343.000000 4782582047729166336.000000  ...  Delhi    Delhi

[5 rows x 13 columns]

## Obsservations :
  1. mutiple device IDs found in cities where lat and longs are NULL
     a. Visakhapatnam - mutiple device
     b. Araria - one Device
     c. Bagaha - one device
     d. Delhi - mutiple device
     e. Indore - multiple device
     f. Pune - mutiple device
     g. Moga - one device
     h. Jaipur - Multiple device
     i. Chennai - Multiple Device

### Cities with mutiple device ID matching for lat-long

In [0]:
##pd.options.display.float_format = '{:.3f}'.format

In [0]:
##np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

In [72]:
lat_long.query('city_x == "Visakhapatnam"').device_id.unique()

array([ 5518659601894558720.000, -6033798388179802112.000,
        4865606571395668992.000])

In [73]:
lat_long.query('city_x == "Araria"').device_id.unique()

array([ 1320050977019711232.000])

In [64]:
lat_long.query('city_x == "Bagaha"').device_id.unique()

array([ 3099168546198768640.000])

In [44]:
lat_long.query('city_x == "Delhi"').device_id.unique()

array([ 4782582047729166336.000,  1779631023439405312.000,
        5375599021847303168.000])

In [45]:
lat_long.query('city_x == "Indore"').device_id.unique()

array([ 2350979402202438656.000, -8790560034584249344.000,
        3738280493453803008.000])

In [46]:
lat_long.query('city_x == "Pune"').device_id.unique()

array([ 7018600380123445248.000,  5115185276392512512.000,
       -7364840628879980544.000])

In [43]:
lat_long.query('city_x == "Moga"').device_id.unique()

array([ 6774071338248977408.000])

In [47]:
lat_long.query('city_x == "Jaipur"').device_id.unique()

array([ 4580179444377398272.000,  305848775386534912.000,
        4375039830232869888.000])

In [48]:
lat_long.query('city_x == "Chennai"').device_id.unique()

array([ 7662139143719919616.000,  7983871429718484992.000,
        5731369272434022400.000])

In [66]:
#lat_long.query('city_x == "Chennai"')    ##Araria,Visakhapatnam,Bagaha,Delhi,Indore,Pune,Moga,Jaipur
events.query('device_id == 3099168546198768640.000 and longitude.isnull()',engine='python')


event_id                  device_id  ...    city  state
3025040  470684.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025139 1105481.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025158 1237993.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025206 1517868.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025251 1788655.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025256 1840867.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025276 1952050.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025296 2070981.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025423 2788384.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025458 3014889.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025460 3024797.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025483 3123229.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025508 3212639.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3025513 3219204.000000 3099168546198768640.000000  ...  Bagaha  Bihar

[14 rows x 7 columns]

In [0]:
dev_lat = events[(events['city'] == "Bagaha") & (events['longitude'].notnull())] 

In [88]:
dev_lat.head()  

event_id                  device_id  ...    city  state
3024968 24727.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3024969 26306.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3024970 26308.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3024971 30838.000000 3099168546198768640.000000  ...  Bagaha  Bihar
3024972 57459.000000 3099168546198768640.000000  ...  Bagaha  Bihar

[5 rows x 7 columns]

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 3099168546198768640.000000) & (events['city'] == 'Bagaha'),'longitude']=84.1409
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 3099168546198768640.000000) & (events['city'] == 'Bagaha'),'latitude']=27.177397

In [0]:
events.query('device_id == 3099168546198768640.000 and longitude.isnull()',engine='python')

In [98]:
events.query('device_id == 1320050977019711232.000 and longitude.isnull()',engine='python')

event_id                  device_id  ...    city  state
3023134  570151.000000 1320050977019711232.000000  ...  Araria  Bihar
3023168  812975.000000 1320050977019711232.000000  ...  Araria  Bihar
3023190  947811.000000 1320050977019711232.000000  ...  Araria  Bihar
3023294 1579192.000000 1320050977019711232.000000  ...  Araria  Bihar
3023319 1716552.000000 1320050977019711232.000000  ...  Araria  Bihar
3023321 1729997.000000 1320050977019711232.000000  ...  Araria  Bihar
3023341 1837824.000000 1320050977019711232.000000  ...  Araria  Bihar
3023372 2078331.000000 1320050977019711232.000000  ...  Araria  Bihar
3023382 2171000.000000 1320050977019711232.000000  ...  Araria  Bihar
3023467 2779303.000000 1320050977019711232.000000  ...  Araria  Bihar
3023479 2828327.000000 1320050977019711232.000000  ...  Araria  Bihar
3023499 2998755.000000 1320050977019711232.000000  ...  Araria  Bihar
3023505 3052608.000000 1320050977019711232.000000  ...  Araria  Bihar
3023514 3079282.000000 1320050977019711232.000000  ...  Araria  Bihar

[14 rows x 7 columns]

In [100]:
araria_lat = events[(events['city'] == "Araria") & (events['longitude'].notnull())] 
araria_lat.head()

event_id                  device_id  ...    city  state
3023049 24397.000000 1320050977019711232.000000  ...  Araria  Bihar
3023050 34725.000000 1320050977019711232.000000  ...  Araria  Bihar
3023051 35264.000000 1320050977019711232.000000  ...  Araria  Bihar
3023052 35267.000000 1320050977019711232.000000  ...  Araria  Bihar
3023053 38057.000000 1320050977019711232.000000  ...  Araria  Bihar

[5 rows x 7 columns]

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 1320050977019711232.000000) & (events['city'] == 'Araria'),'longitude']=87.570736
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 1320050977019711232.000000) & (events['city'] == 'Araria'),'latitude']=26.211919

In [103]:
moga_lat = events[(events['city'] == "Moga") & (events['longitude'].notnull())] 
moga_lat.head()

event_id                  device_id  ...  city   state
3011425 22521.000000 6774071338248977408.000000  ...  Moga  Punjab
3011426 22522.000000 6774071338248977408.000000  ...  Moga  Punjab
3011427 29086.000000 6774071338248977408.000000  ...  Moga  Punjab
3011428 30230.000000 6774071338248977408.000000  ...  Moga  Punjab
3011429 30231.000000 6774071338248977408.000000  ...  Moga  Punjab

[5 rows x 7 columns]

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 6774071338248977408.000000) & (events['city'] == 'Moga'),'longitude']=75.268748
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 6774071338248977408.000000) & (events['city'] == 'Moga'),'latitude']=30.904178

In [106]:
visa_lat = events[(events['city'] == "Visakhapatnam") & (events['longitude'].notnull())] 
visa_lat.head()

event_id                   device_id  ...           city          state
1868677  5985.000000 -7971778470363550720.000000  ...  Visakhapatnam  AndhraPradesh
1868678 56595.000000 -7971778470363550720.000000  ...  Visakhapatnam  AndhraPradesh
1868679 75863.000000 -7971778470363550720.000000  ...  Visakhapatnam  AndhraPradesh
1868680 81849.000000 -7971778470363550720.000000  ...  Visakhapatnam  AndhraPradesh
1868681 97846.000000 -7971778470363550720.000000  ...  Visakhapatnam  AndhraPradesh

[5 rows x 7 columns]

In [119]:
events.query('city == "Visakhapatnam" and longitude.notnull() and device_id == "5518659601894558720.000"',engine='python')   
##5518659601894558720.000, -6033798388179802112.000,4865606571395668992.000

event_id                  device_id  ...           city          state
1901585    6529.000000 5518659601894558720.000000  ...  Visakhapatnam  AndhraPradesh
1901586    7197.000000 5518659601894558720.000000  ...  Visakhapatnam  AndhraPradesh
1901587    7419.000000 5518659601894558720.000000  ...  Visakhapatnam  AndhraPradesh
1901588    7843.000000 5518659601894558720.000000  ...  Visakhapatnam  AndhraPradesh
1901589    8122.000000 5518659601894558720.000000  ...  Visakhapatnam  AndhraPradesh
...                ...                        ...  ...            ...            ...
1903091 3243990.000000 5518659601894558720.000000  ...  Visakhapatnam  AndhraPradesh
1903092 3247433.000000 5518659601894558720.000000  ...  Visakhapatnam  AndhraPradesh
1903093 3250247.000000 5518659601894558720.000000  ...  Visakhapatnam  AndhraPradesh
1903094 3250657.000000 5518659601894558720.000000  ...  Visakhapatnam  AndhraPradesh
1903095 3251317.000000 5518659601894558720.000000  ...  Visakhapatnam  AndhraPradesh

[1490 rows x 7 columns]

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == -6033798388179802112.000) & (events['city'] == 'Visakhapatnam'),'longitude']=83.319787
events.loc[(events['latitude'].isnull()) & (events['device_id'] == -6033798388179802112.000) & (events['city'] == 'Visakhapatnam'),'latitude']=17.816579

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 4865606571395668992.000000) & (events['city'] == 'Visakhapatnam'),'longitude']=83.351442
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 4865606571395668992.000000) & (events['city'] == 'Visakhapatnam'),'latitude']=17.772252

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 5518659601894558720.000000) & (events['city'] == 'Visakhapatnam'),'longitude']=83.384242
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 5518659601894558720.000000) & (events['city'] == 'Visakhapatnam'),'latitude']=17.817945

In [123]:
delhi_lat = events[(events['city'] == "Delhi") & (events['longitude'].notnull())] 
delhi_lat.head()

event_id                device_id  ...   city  state
0     1.000000 29182687948017176.000000  ...  Delhi  Delhi
1  7104.000000 29182687948017176.000000  ...  Delhi  Delhi
2 29661.000000 29182687948017176.000000  ...  Delhi  Delhi
3 33133.000000 29182687948017176.000000  ...  Delhi  Delhi
4 38980.000000 29182687948017176.000000  ...  Delhi  Delhi

[5 rows x 7 columns]

In [133]:
events.query('city == "Delhi" and longitude.notnull() and device_id == "2350979402202438656.000"',engine='python')   
##4782582047729166336.000,  1779631023439405312.000,5375599021847303168.000

event_id                  device_id  ...    city          state
2209248   10320.000000 2350979402202438656.000000  ...  Indore  MadhyaPradesh
2209249   11363.000000 2350979402202438656.000000  ...  Indore  MadhyaPradesh
2209250   11973.000000 2350979402202438656.000000  ...  Indore  MadhyaPradesh
2209251   14729.000000 2350979402202438656.000000  ...  Indore  MadhyaPradesh
2209252   16260.000000 2350979402202438656.000000  ...  Indore  MadhyaPradesh
...                ...                        ...  ...     ...            ...
2210033 3229494.000000 2350979402202438656.000000  ...  Indore  MadhyaPradesh
2210034 3233529.000000 2350979402202438656.000000  ...  Indore  MadhyaPradesh
2210035 3237666.000000 2350979402202438656.000000  ...  Indore  MadhyaPradesh
2210036 3239613.000000 2350979402202438656.000000  ...  Indore  MadhyaPradesh
2210037 3242825.000000 2350979402202438656.000000  ...  Indore  MadhyaPradesh

[770 rows x 7 columns]

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 5375599021847303168.000000) & (events['city'] == 'Delhi'),'longitude']=77.283447
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 5375599021847303168.000000) & (events['city'] == 'Delhi'),'latitude']=28.718392

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 4782582047729166336.000) & (events['city'] == 'Delhi'),'longitude']=77.225220
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 4782582047729166336.000) & (events['city'] == 'Delhi'),'latitude']=28.718379

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 1779631023439405312.000) & (events['city'] == 'Delhi'),'longitude']=77.235416
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 1779631023439405312.000) & (events['city'] == 'Delhi'),'latitude']=28.738901

In [137]:
events.query('city == "Indore" and longitude.notnull() and device_id == "3738280493453803008.000"',engine='python')   
##2350979402202438656.000, -8790560034584249344.000,3738280493453803008.000

event_id                  device_id  ...    city          state
2231134   10819.000000 3738280493453803008.000000  ...  Indore  MadhyaPradesh
2231135   19593.000000 3738280493453803008.000000  ...  Indore  MadhyaPradesh
2231136   21130.000000 3738280493453803008.000000  ...  Indore  MadhyaPradesh
2231137   27808.000000 3738280493453803008.000000  ...  Indore  MadhyaPradesh
2231138   37083.000000 3738280493453803008.000000  ...  Indore  MadhyaPradesh
...                ...                        ...  ...     ...            ...
2231926 3228938.000000 3738280493453803008.000000  ...  Indore  MadhyaPradesh
2231927 3237217.000000 3738280493453803008.000000  ...  Indore  MadhyaPradesh
2231928 3242200.000000 3738280493453803008.000000  ...  Indore  MadhyaPradesh
2231929 3246815.000000 3738280493453803008.000000  ...  Indore  MadhyaPradesh
2231930 3251471.000000 3738280493453803008.000000  ...  Indore  MadhyaPradesh

[776 rows x 7 columns]

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 2350979402202438656.000000) & (events['city'] == 'Indore'),'longitude']=75.888474
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 2350979402202438656.000000) & (events['city'] == 'Indore'),'latitude']=22.745063

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == -8790560034584249344.000) & (events['city'] == 'Indore'),'longitude']=75.933778
events.loc[(events['latitude'].isnull()) & (events['device_id'] == -8790560034584249344.000) & (events['city'] == 'Indore'),'latitude']=22.761965

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 3738280493453803008.000) & (events['city'] == 'Indore'),'longitude']=75.937988
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 3738280493453803008.000) & (events['city'] == 'Indore'),'latitude']=22.762010

In [144]:
events.query('city == "Pune" and longitude.notnull() and device_id == "-7364840628879980544.000"',engine='python')   
##7018600380123445248.000,  5115185276392512512.000, -7364840628879980544.000

event_id                   device_id  ...  city        state
1194031    3999.000000 -7364840628879980544.000000  ...  Pune  Maharashtra
1194032    4236.000000 -7364840628879980544.000000  ...  Pune  Maharashtra
1194033    5483.000000 -7364840628879980544.000000  ...  Pune  Maharashtra
1194034    6811.000000 -7364840628879980544.000000  ...  Pune  Maharashtra
1194035   10469.000000 -7364840628879980544.000000  ...  Pune  Maharashtra
...                ...                         ...  ...   ...          ...
1196651 3248539.000000 -7364840628879980544.000000  ...  Pune  Maharashtra
1196652 3248858.000000 -7364840628879980544.000000  ...  Pune  Maharashtra
1196653 3250575.000000 -7364840628879980544.000000  ...  Pune  Maharashtra
1196654 3250707.000000 -7364840628879980544.000000  ...  Pune  Maharashtra
1196655 3252493.000000 -7364840628879980544.000000  ...  Pune  Maharashtra

[2604 rows x 7 columns]

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 7018600380123445248.000000) & (events['city'] == 'Pune'),'longitude']=73.926223
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 7018600380123445248.000000) & (events['city'] == 'Pune'),'latitude']=18.575747

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 5115185276392512512.000000) & (events['city'] == 'Pune'),'longitude']=73.888680
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 5115185276392512512.000000) & (events['city'] == 'Pune'),'latitude']=18.556741

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == -7364840628879980544.000) & (events['city'] == 'Pune'),'longitude']=73.931944
events.loc[(events['latitude'].isnull()) & (events['device_id'] == -7364840628879980544.000) & (events['city'] == 'Pune'),'latitude']=18.540740

In [151]:
events.query('city == "Jaipur" and longitude.notnull() and device_id == "4375039830232869888.000"',engine='python')   
##4580179444377398272.000,  305848775386534912.000,4375039830232869888.000

event_id                  device_id  ...    city      state
2576673   18788.000000 4375039830232869888.000000  ...  Jaipur  Rajasthan
2576674   22962.000000 4375039830232869888.000000  ...  Jaipur  Rajasthan
2576675   42168.000000 4375039830232869888.000000  ...  Jaipur  Rajasthan
2576676   43723.000000 4375039830232869888.000000  ...  Jaipur  Rajasthan
2576677   52886.000000 4375039830232869888.000000  ...  Jaipur  Rajasthan
...                ...                        ...  ...     ...        ...
2577266 3219460.000000 4375039830232869888.000000  ...  Jaipur  Rajasthan
2577267 3222399.000000 4375039830232869888.000000  ...  Jaipur  Rajasthan
2577268 3236251.000000 4375039830232869888.000000  ...  Jaipur  Rajasthan
2577270 3249786.000000 4375039830232869888.000000  ...  Jaipur  Rajasthan
2577271 3252894.000000 4375039830232869888.000000  ...  Jaipur  Rajasthan

[577 rows x 7 columns]

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 4580179444377398272.000000) & (events['city'] == 'Jaipur'),'longitude']=75.835756
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 4580179444377398272.000000) & (events['city'] == 'Jaipur'),'latitude']=26.960220

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 305848775386534912.000000) & (events['city'] == 'Jaipur'),'longitude']=75.865534
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 305848775386534912.000000) & (events['city'] == 'Jaipur'),'latitude']=26.987566

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 4375039830232869888.000) & (events['city'] == 'Jaipur'),'longitude']=75.824489
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 4375039830232869888.000) & (events['city'] == 'Jaipur'),'latitude']=26.980345

In [158]:
events.query('city == "Chennai" and longitude.notnull() and device_id == "5731369272434022400.000"',engine='python')   
##7662139143719919616.000,  7983871429718484992.000, 5731369272434022400.000

event_id                  device_id  ...     city      state
1648184     938.000000 5731369272434022400.000000  ...  Chennai  TamilNadu
1648185    2199.000000 5731369272434022400.000000  ...  Chennai  TamilNadu
1648186    8008.000000 5731369272434022400.000000  ...  Chennai  TamilNadu
1648187   11003.000000 5731369272434022400.000000  ...  Chennai  TamilNadu
1648188   12856.000000 5731369272434022400.000000  ...  Chennai  TamilNadu
...                ...                        ...  ...      ...        ...
1651713 3250778.000000 5731369272434022400.000000  ...  Chennai  TamilNadu
1651714 3250865.000000 5731369272434022400.000000  ...  Chennai  TamilNadu
1651715 3251010.000000 5731369272434022400.000000  ...  Chennai  TamilNadu
1651716 3251127.000000 5731369272434022400.000000  ...  Chennai  TamilNadu
1651717 3252640.000000 5731369272434022400.000000  ...  Chennai  TamilNadu

[3492 rows x 7 columns]

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 7662139143719919616.000000) & (events['city'] == 'Chennai'),'longitude']=80.309272
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 7662139143719919616.000000) & (events['city'] == 'Chennai'),'latitude']=13.149176

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 7983871429718484992.000000	) & (events['city'] == 'Chennai'),'longitude']=80.335435
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 7983871429718484992.000000	) & (events['city'] == 'Chennai'),'latitude']=13.189053

In [0]:
events.loc[(events['longitude'].isnull()) & (events['device_id'] == 5731369272434022400.000	) & (events['city'] == 'Chennai'),'longitude']=80.343613
events.loc[(events['latitude'].isnull()) & (events['device_id'] == 5731369272434022400.000	) & (events['city'] == 'Chennai'),'latitude']=13.153332

In [162]:
total = events.isnull().sum().sort_values(ascending=False)
percent = (events.isnull().sum()/events.isnull().count()).sort_values(ascending=False)
missing_data_events = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data_events.head(20)
print(missing_data_events)

           Total  Percent
device_id    453 0.000139
state        377 0.000116
city           0 0.000000
latitude       0 0.000000
longitude      0 0.000000
timestamp      0 0.000000
event_id       0 0.000000


### Data Processing for records where state is NULL

In [163]:
# creating bool series True for NaN values  
bool_series = pd.isnull(events["state"])  
    
# filtering data  
# displaying data only with state = NaN  
events[bool_series]


event_id                   device_id  ...         city  state
16649    191851.000000 -6242501228649113600.000000  ...        Delhi    NaN
16836    341684.000000 -6242501228649113600.000000  ...        Delhi    NaN
17247    658755.000000 -6242501228649113600.000000  ...        Delhi    NaN
17339    720866.000000 -6242501228649113600.000000  ...        Delhi    NaN
17696    983707.000000 -6242501228649113600.000000  ...        Delhi    NaN
...                ...                         ...  ...          ...    ...
3078315 2805999.000000 -5858653205052383232.000000  ...  Gangarampur    NaN
3078335 2873949.000000 -5858653205052383232.000000  ...  Gangarampur    NaN
3078359 3057454.000000 -5858653205052383232.000000  ...  Gangarampur    NaN
3078372 3109058.000000 -5858653205052383232.000000  ...  Gangarampur    NaN
3078387 3188932.000000 -5858653205052383232.000000  ...  Gangarampur    NaN

[377 rows x 7 columns]

In [164]:
events[bool_series].groupby('city').count()

event_id  device_id  timestamp  longitude  latitude  state
city                                                                     
Arambagh             16         16         16         16        16      0
Channapatna          14         14         14         14        14      0
Chennai              47         47         47         47        47      0
Delhi                64         64         64         64        64      0
Gangarampur          26         26         26         26        26      0
Indore               51         51         51         51        51      0
Jaipur               49         49         49         49        49      0
Pune                 63         63         63         63        63      0
Visakhapatnam        47         47         47         47        47      0

In [0]:
events[(events['city'] == "Visakhapatnam")]    ##Arambagh,Channapatna,Chennai,Delhi,Gangarampur,Indore,Jaipur,Pune,Visakhapatnam	

event_id     device_id  ...           city          state
1868677     5985.0 -7.971778e+18  ...  Visakhapatnam  AndhraPradesh
1868678    56595.0 -7.971778e+18  ...  Visakhapatnam  AndhraPradesh
1868679    75863.0 -7.971778e+18  ...  Visakhapatnam  AndhraPradesh
1868680    81849.0 -7.971778e+18  ...  Visakhapatnam  AndhraPradesh
1868681    97846.0 -7.971778e+18  ...  Visakhapatnam  AndhraPradesh
...            ...           ...  ...            ...            ...
2194869  2175248.0  8.677316e+18  ...  Visakhapatnam  AndhraPradesh
2195335   723262.0  8.388565e+18  ...  Visakhapatnam  AndhraPradesh
2197469  2012407.0  8.018174e+18  ...  Visakhapatnam  AndhraPradesh
2197622  2330241.0 -6.978865e+18  ...  Visakhapatnam  AndhraPradesh
2197800  2957421.0  2.445678e+17  ...  Visakhapatnam  AndhraPradesh

[235772 rows x 7 columns]

In [0]:
events[(events['state'].isnull()) & (events['city'] == "Delhi")]
##events[(events['state'] == "Delhi")]


event_id     device_id            timestamp  ...   latitude   city state
16649   191851.0 -6.242501e+18  2016-05-02 05:50:53  ...  28.749820  Delhi   NaN
16836   341684.0 -6.242501e+18  2016-05-02 08:37:46  ...  28.749820  Delhi   NaN
17247   658755.0 -6.242501e+18  2016-05-02 10:10:57  ...  28.749820  Delhi   NaN
17339   720866.0 -6.242501e+18  2016-05-02 20:55:28  ...  28.749820  Delhi   NaN
17696   983707.0 -6.242501e+18  2016-05-03 10:25:17  ...  28.749820  Delhi   NaN
...          ...           ...                  ...  ...        ...    ...   ...
67781  2649541.0 -3.746249e+18  2016-05-05 10:43:47  ...  28.756094  Delhi   NaN
67832  2683860.0 -3.746249e+18  2016-05-05 20:57:45  ...  28.756094  Delhi   NaN
68040  2843138.0 -3.746249e+18  2016-05-07 00:02:38  ...  28.756094  Delhi   NaN
68268  3041827.0 -3.746249e+18  2016-05-07 00:33:08  ...  28.756094  Delhi   NaN
68463  3185465.0 -3.746249e+18  2016-05-04 14:44:53  ...  28.756094  Delhi   NaN

[64 rows x 7 columns]

In [0]:
events.head()

event_id               device_id  ...   city  state
0     1.000000  2.9182687948017176e+16  ...  Delhi  Delhi
1  7104.000000  2.9182687948017176e+16  ...  Delhi  Delhi
2 29661.000000  2.9182687948017176e+16  ...  Delhi  Delhi
3 33133.000000  2.9182687948017176e+16  ...  Delhi  Delhi
4 38980.000000  2.9182687948017176e+16  ...  Delhi  Delhi

[5 rows x 7 columns]

In [0]:
events["longitude"] = events["longitude"].round(6).astype(str)
events["latitude"] = events["latitude"].round(6).astype(str)


In [74]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3252950 entries, 0 to 3252949
Data columns (total 7 columns):
event_id     float64
device_id    float64
timestamp    object
longitude    float64
latitude     float64
city         object
state        object
dtypes: float64(4), object(3)
memory usage: 173.7+ MB


In [75]:
dl = events[(events['city'] == "Pune")]
dl.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 317276 entries, 1036301 to 1428900
Data columns (total 7 columns):
event_id     317276 non-null float64
device_id    317204 non-null float64
timestamp    317276 non-null object
longitude    317213 non-null float64
latitude     317213 non-null float64
city         317276 non-null object
state        317213 non-null object
dtypes: float64(4), object(3)
memory usage: 19.4+ MB


## Observations 
1. 377 states are blank but cities found for such entries. On the basis of city we can update states as follows
1. Arambaugh  - WestBengal
2. Channapatna - Karnataka
3. Chennai - Tamilnadu
4. Delhi - Delhi
5. Gangarampur - WestBengal
6. Indore - Madhyapradesh
7. Jaipur - Rajasthan
8. Pune - Maharashtra
9. Visakhapatnam - Andhrapradesh


In [0]:
events[bool_series].groupby('city').count()

event_id  device_id  timestamp  longitude  latitude  state
city                                                                     
Arambagh             16         16         16         16        16      0
Channapatna          14         14         14         14        14      0
Chennai              47         47         47         47        47      0
Delhi                64         64         64         64        64     64
Gangarampur          26         26         26         26        26      0
Indore               51         51         51         51        51      0
Jaipur               49         49         49         49        49      0
Pune                 63         63         63         63        63      0
Visakhapatnam        47         47         47         47        47      0

In [0]:
events.loc[(events['state'].isnull()) & (events['city'] == 'Arambagh'),'state']='WestBengal'
events.loc[(events['state'].isnull()) & (events['city'] == 'Channapatna'),'state']='Karnataka'
events.loc[(events['state'].isnull()) & (events['city'] == 'Chennai'),'state']='TamilNadu'
events.loc[(events['state'].isnull()) & (events['city'] == 'Gangarampur'),'state']='WestBengal'
events.loc[(events['state'].isnull()) & (events['city'] == 'Indore'),'state']='MadhyaPradesh'
events.loc[(events['state'].isnull()) & (events['city'] == 'Jaipur'),'state']='Rajasthan'
events.loc[(events['state'].isnull()) & (events['city'] == 'Pune'),'state']='Maharashtra'
events.loc[(events['state'].isnull()) & (events['city'] == 'Visakhapatnam'),'state']='AndhraPradesh'
events.loc[(events['state'].isnull()) & (events['city'] == 'Delhi'),'state']='Delhi'

In [166]:
events[(events['state'].isnull())]

Empty DataFrame
Columns: [event_id, device_id, timestamp, longitude, latitude, city, state]
Index: []

In [167]:
##missing data in events
total = events.isnull().sum().sort_values(ascending=False)
percent = (events.isnull().sum()/events.isnull().count()).sort_values(ascending=False)
missing_data_events = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data_events.head(20)
print(missing_data_events)

           Total  Percent
device_id    453 0.000139
state          0 0.000000
city           0 0.000000
latitude       0 0.000000
longitude      0 0.000000
timestamp      0 0.000000
event_id       0 0.000000


In [200]:
events.groupby('state')['city'].value_counts()

state                     city         
AndamanandNicobarIslands  PortBlair          1515
AndhraPradesh             Visakhapatnam    235772
                          Bodhan             1539
                          Sattenapalle       1521
                          Kodar              1488
                                            ...  
WestBengal                Rajpur              439
                          Siuri               433
                          DumDum              423
                          AlipurDuar          383
                          Khardaha            370
Name: city, Length: 943, dtype: int64

In [209]:
plt.figure(figsize = (15, 6))
events.groupby('state')['city'].count().sort_values(ascending=True).plot(kind='bar', color='g')
plt.ylabel('Count')

Text(0, 0.5, 'Count')

In [203]:
plt.figure(figsize = (15, 6))
gender_age_train.groupby('age_group')['age'].count().sort_values(ascending=True).plot(kind='bar', color='g')
plt.ylabel('Count')


Text(0, 0.5, 'Count')

# New Section

Observation :
1. Age grouping is contactinated with Gender due to which group analyis misguiding. Age Grouping is different for male and female

In [0]:
##gender_age_train['gendersub'] =gender_age_train.age_group.str.slice(1,6)
##gender_age_train.head()

In [0]:
print("distinct age_group:", set(gender_age_train['age_group']))


distinct age_group: {'F24-26', 'M27-28', 'M32-38', 'M29-31', 'M22-', 'F43+', 'M23-26', 'F33-42', 'F29-32', 'M39+', 'F23-', 'F27-28'}


In [0]:
pd.crosstab(gender_age_train['age'],gender_age_train['age_group'] )

age_group  F23-  F24-26  F27-28  F29-32  ...  M27-28  M29-31  M32-38  M39+
age                                      ...                              
1             0       0       0       0  ...       0       0       0     0
6             0       0       0       0  ...       0       0       0     0
10            2       0       0       0  ...       0       0       0     0
11            4       0       0       0  ...       0       0       0     0
12            5       0       0       0  ...       0       0       0     0
..          ...     ...     ...     ...  ...     ...     ...     ...   ...
88            0       0       0       0  ...       0       0       0     2
89            0       0       0       0  ...       0       0       0     0
90            0       0       0       0  ...       0       0       0     1
94            0       0       0       0  ...       0       0       0     0
96            0       0       0       0  ...       0       0       0     0

[85 rows x 12 columns]

In [0]:
##gender_age_train.device_id=gender_age_train.astype(str)
##phone_brand.device_id = phone_brand.astype(str)
##events.device_id = events.astype(str)
##events.event_id = events.astype(str)

In [204]:
gender_age_train.hist(by='gender',column = 'age',figsize=(10,10))

array([<matplotlib.axes._subplots.AxesSubplot object at 0x7f64748a04a8>,
      dtype=object)

In [199]:
phone_brand.groupby('model')['device_id'].count().sort_values(ascending=False).head(20)

model
红米note           3500
MI 3             2739
MI 2S            2547
Galaxy Note 3    2378
MI 4             2256
Galaxy S4        1910
Galaxy Note 2    1877
荣耀6              1471
荣耀畅玩4X           1279
荣耀3C             1206
红米1S             1191
红米               1168
Galaxy S3        1156
Mate 7           1125
魅蓝NOTE           1026
红米2               941
红米Note2           903
MX3               842
Galaxy S5         827
荣耀6 Plus          815
Name: device_id, dtype: int64

In [0]:
print("distinct Model:", set(phone_brand['model']))

distinct Model: {'E613M', '606w', '黄金斗士S8畅玩版', 'Z7 Mini', '锋尚', 'MI 1S', 'I9118', 'A820e', '魅蓝Note 2', 'L1', 'BM001', 'A760', 'F103S', '小星星', 'GN700T', 'Galaxy J7', 'X1S', 'U701T', 'T1', '3S', '荣耀4A', 'Y610-U00', '小辣椒 M3', 'MediaPad M2-801W', '领世旗舰3', 'memo 5S', 'X3S', 'A320t', 'T00G', 'Galaxy Note 3 Lite', '7i', '红米note增强版', 'OKA51', 'MK260', 'Galaxy Y', 'Y17W', 'T528d', 'Y618-T00', 'U81t', 'I635T', 'X805', 'Galaxy S4 Mini', 'Q302C', 'V923', 'Q503U', '小辣椒 9', 'L1 mini', 'N1W', 'MOMO9', 'V188', 'Galaxy Fame', 'Moto G', 'D557', 'One E8', 'V981', 'Q301C', 'ELIFE S5.5', 'U880S', 'Y51', 'GN705', 'B199', 'W2014', 'X3L', 'S7568', '小鲜2', 'One X', 'Desire 816x', 'Optimus G', 'A328t', 'Moto Turbo', 'Xperia T2 Ultra', 'E5', 'GN150', '7236', 'Galaxy Ace 4', 'T20', 'P8 Lite', 'Blade C', 'U936', '5956', 'Galaxy On5', 'VT898S', '5879', '么么哒3S', 'XT928', 'S5000', 'N821', 'Galaxy Win Pro', 'GN810', '8712', 'Axon天机', 'T9', 'Xperia TX', 'Y613', 'Galaxy S Advance', '8721', 'K900', '荣耀平板T1-823L', 'Desire 

In [0]:
print("distinct brand:", set(phone_brand['brand']))

distinct brand: {'易派', '凯利通', '艾优尼', '酷比', '诺基亚', '普耐尔', '谷歌', '联想 ', '富可视', '诺亚信', '唯比', '大可乐', '一加', 'vivo', '台电', '大显', '赛博宇华', '瑞高', 'E派', '酷珀', '世纪星', '米歌', '飞利浦', '长虹', '魅族', '优购', '飞秒', '海尔', '维图', '欧比', '欧新', '奇酷', '华为', '朵唯', '天语', '青橙', '青葱', '糯米', '先锋', '爱派尔', '西门子', '虾米', '优语', 'LOGO', '果米', '西米', '德赛', '广信', '蓝魔', '小米', '酷派', '本为', '小杨树', '鲜米', '惠普', '聆韵', '海信', '米奇', 'PPTV', 'Lovme', '至尊宝', '宝捷讯', 'E人E本', '丰米', '纽曼', '邦华', 'SUGAR', '帷幄', '奥克斯', '黑米', '百立丰', 'TCL', '锤子', 'LG', '尼比鲁', '昂达', '大Q', '欧奇', '夏新', '中国移动', '贝尔丰', '波导', '三星', '梦米', '欧沃', '欧乐迪', '乡米', '瑞米', '康佳', '糖葫芦', '优米', '酷比魔方', 'HTC', '沃普丰', '亿通', '百加', '美图', '乐视', '努比亚', 'ZUK', '恒宇丰', '首云', '金星数码', '语信', 'OPPO', '唯米', '华硕', '智镁', '神舟', 'MIL', '摩乐', '斐讯', '欧博信', '白米', '基伍', '摩托罗拉'}


In [0]:
phone_brand['model'].value_counts().count()

1467

In [0]:
phone_brand['brand'].value_counts().count()

116

In [0]:
phone_brand.groupby('brand')['model'].value_counts().count()   ##.sort_values(ascending=False).plot(kind='bar', color='g')

1522

In [0]:
df = pd.crosstab(phone_brand['brand'],phone_brand['model'] ).sum()
df.tail()

model
麦芒4          201
黄金斗士A8       150
黄金斗士Note8     33
黄金斗士S8畅玩版      6
黄金斗士青春版        5
dtype: int64

In [0]:
!pip install googletrans

In [0]:
# Language Translator
from googletrans import Translator  # Import Translator module from googletrans package

translator = Translator() # Create object of Translator.

In [0]:
d = []
translatedList = translator.translate(['首云', '酷珀', '欧乐迪', '诺亚信', '长虹', '先锋', '摩乐', '奥克斯', '华硕', '尼比鲁', '智镁', '诺基亚', '鲜米', 
                                       '惠普', '天语', '瑞米', '神舟', '糯米', '艾优尼', '白米', '努比亚', '金星数码', '凯利通', '斐讯', 'Lovme', '沃普丰', 
                                       '帷幄', 'LG', '欧比', '聆韵', '糖葫芦', 'LOGO', '唯比', '富可视', '奇酷', '普耐尔', '德赛', '联想 ', '海尔', '百加', 
                                       '飞秒', 'PPTV', '广信', '瑞高', '海信', 'OPPO', '朵唯', '百立丰', '谷歌', 'MIL', '青橙', '世纪星', '易派', '三星', 
                                       '青葱', 'ZUK', '大显', '美图', '邦华', '宝捷讯', '康佳', '黑米', '亿通', '魅族', '酷比', 'HTC', '酷派', '乡米', 
                                       '摩托罗拉', '梦米', '唯米', 'TCL', '基伍', '爱派尔', '一加', '恒宇丰', '米歌', '至尊宝', '夏新', '优米', 'E派', '波导', 
                                       '昂达', '本为', '优购', '飞利浦', '纽曼', '赛博宇华', '优语', '欧奇', '华为', '虾米', '蓝魔', 'E人E本', '大Q', '乐视', 
                                       '果米', '小杨树', '欧新', '台电', 'vivo', '欧沃', '西米', '丰米', '欧博信', '酷比魔方', 'SUGAR', '锤子', '西门子', '维图',
                                       '米奇', '小米', '大可乐', '语信', '贝尔丰', '中国移动'])

for translated in translatedList:
     d.append({'brand': translated.origin, 'converted_brand':translated.text})
     

df1 = pd.DataFrame(data=d)

In [0]:
df1

brand  converted_brand
0      首云          Shouyun
1      酷珀            Koku珀
2     欧乐迪          Oral-Di
3     诺亚信      Noah letter
4      长虹        Changhong
..    ...              ...
111    小米           Millet
112   大可乐         Big Cola
113    语信  Language letter
114   贝尔丰       Bellefonte
115  中国移动     China Mobile

[116 rows x 2 columns]

In [0]:
phone_conv = pd.merge(phone_brand,df1, how='inner', left_on='brand', right_on='brand')
phone_conv.head()


device_id brand      model converted_brand
0  1877775838486905855  vivo        Y13            vivo
1 -8705713195059105949  vivo       X6 L            vivo
2  7284092388756598809  vivo        Y35            vivo
3  -298209719519394007  vivo  Xperia SL            vivo
4  5191524460861112478  vivo       Y17T            vivo

In [0]:
phone_conv.shape

(87726, 4)

In [0]:
data = set(phone_brand['model'])
data

{'E613M',
 '606w',
 '黄金斗士S8畅玩版',
 'Z7 Mini',
 '锋尚',
 'MI 1S',
 'I9118',
 'A820e',
 '魅蓝Note 2',
 'L1',
 'BM001',
 'A760',
 'F103S',
 '小星星',
 'GN700T',
 'Galaxy J7',
 'X1S',
 'U701T',
 'T1',
 '3S',
 '荣耀4A',
 'Y610-U00',
 '小辣椒 M3',
 'MediaPad M2-801W',
 '领世旗舰3',
 'memo 5S',
 'X3S',
 'A320t',
 'T00G',
 'Galaxy Note 3 Lite',
 '7i',
 '红米note增强版',
 'OKA51',
 'MK260',
 'Galaxy Y',
 'Y17W',
 'T528d',
 'Y618-T00',
 'U81t',
 'I635T',
 'X805',
 'Galaxy S4 Mini',
 'Q302C',
 'V923',
 'Q503U',
 '小辣椒 9',
 'L1 mini',
 'N1W',
 'MOMO9',
 'V188',
 'Galaxy Fame',
 'Moto G',
 'D557',
 'One E8',
 'V981',
 'Q301C',
 'ELIFE S5.5',
 'U880S',
 'Y51',
 'GN705',
 'B199',
 'W2014',
 'X3L',
 'S7568',
 '小鲜2',
 'One X',
 'Desire 816x',
 'Optimus G',
 'A328t',
 'Moto Turbo',
 'Xperia T2 Ultra',
 'E5',
 'GN150',
 '7236',
 'Galaxy Ace 4',
 'T20',
 'P8 Lite',
 'Blade C',
 'U936',
 '5956',
 'Galaxy On5',
 'VT898S',
 '5879',
 '么么哒3S',
 'XT928',
 'S5000',
 'N821',
 'Galaxy Win Pro',
 'GN810',
 '8712',
 'Axon天机',
 'T9',
 'Xpe

In [0]:
conv_model =pd.DataFrame(data = set(phone_brand['model']))
conv_model.columns=['model']
conv_model

model
0         E613M
1          606w
2     黄金斗士S8畅玩版
3       Z7 Mini
4            锋尚
...         ...
1462  Y523-L176
1463    火星一号探索版
1464         S6
1465        MX4
1466        V70

[1467 rows x 1 columns]

In [0]:
!pip install langdetect

     |████████████████████████████████| 983kB 5.0MB/s 
  Created wheel for langdetect: filename=langdetect-1.0.8-cp36-none-any.whl size=993193 sha256=93f2346886b8a7d2acbdaebfe12f55ba9a3a1df8c0dce8673f7acfd876287711
  Stored in directory: /root/.cache/pip/wheels/8d/b3/aa/6d99de9f3841d7d3d40a60ea06e6d669e8e5012e6c8b947a57
Successfully built langdetect


In [0]:
from langdetect import detect

In [0]:
translations = {}


for column in conv_model.columns:
    # unique elements of the column
    unique_elements = conv_model[column].unique()
    for element in unique_elements:
       try :
          # add translation to the dictionary
          ##translations[element] = translator.translate('A366t').text
          lang  = detect(element)
          print(element)
          print(lang)
          if (lang == 'en') :
              translations[element] = element
          else :
              translations[element] = translator.translate(element,dest='en').text

       except :
             lang='no'                                                  
             print("This row throws error:", translations[element])                 
             translations.append(lang)    
             translations[element] = element            
        
    



print(translations)

E613M
es
606w
sw
黄金斗士S8畅玩版
ko
Z7 Mini
de
锋尚
zh-cn
MI 1S
de
I9118
it
A820e
hu
魅蓝Note 2
af
L1
ca
BM001
id
A760
hu
F103S
de
小星星
ko
GN700T
vi
Galaxy J7
so
X1S
so
U701T
hr
T1
vi
3S
de
荣耀4A
tl
Y610-U00
cy
小辣椒 M3
ko
MediaPad M2-801W
cy
领世旗舰3
ko
memo 5S
pt
X3S
so
A320t
hu
T00G
en
Galaxy Note 3 Lite
en
7i
af
红米note增强版
no
OKA51
pt
MK260
sw
Galaxy Y
so
Y17W
cy
T528d
id
Y618-T00
cy
U81t
hr
I635T
it
X805
so
Galaxy S4 Mini
so
Q302C
vi
V923
sk
Q503U
so
小辣椒 9
ko
L1 mini
lt
N1W
so
MOMO9
pt
V188
sk
Galaxy Fame
so
Moto G
it
D557
de
One E8
fr
V981
sk
Q301C
vi
ELIFE S5.5
de
U880S
hr
Y51
cy
GN705
so
B199
de
W2014
pl
X3L
ca
S7568
de
小鲜2
ko
One X
fr
Desire 816x
no
Optimus G
lt
A328t
hu
Moto Turbo
lt
Xperia T2 Ultra
ca
E5
es
GN150
so


KeyError: ignored

In [0]:
translator = Translator()

In [0]:
m = []
i= 0
for i in range(len(conv_model)) :
    
     x = conv_model.loc[i, "model"]
     print(x)
     translated = translator.translate(x)

print(translated.origin)
     ##print(translated.text)

       
     
   
    
      ##print(translatedListm)
      ##for translatedm in translatedListm:
      ## m.append({'model': x, 'converted_model':})
     

mf2 = pd.DataFrame(data=m)
    

A366t


JSONDecodeError: ignored

In [0]:
mf2

NameError: ignored

In [0]:
pd.crosstab(phone_conv['converted_brand'],phone_brand['model'] )

model            1100  1105  1107  2  ...  黄金斗士A8  黄金斗士Note8  黄金斗士S8畅玩版  黄金斗士青春版
converted_brand                       ...                                       
A plus              0     0     0  0  ...       0          0          0        0
ASUS                0     0     0  0  ...       0          0          0        0
Ai Unocal           0     0     0  0  ...       0          0          0        0
Amagatarai          0     0     1  0  ...       0          0          0        0
Amoi                0     0     0  0  ...       0          0          0        0
...               ...   ...   ... ..  ...     ...        ...        ...      ...
hammer              0     0     1  0  ...       0          0          0        0
pioneer             0     0     0  0  ...       0          0          0        0
vivo                1     5    10  3  ...      15          3          0        0
waveguide           0     0     0  0  ...       0          0          0        0
亿通                  0     0     0  0  ...       0          0          0        0

[116 rows x 1467 columns]

In [0]:
device_merge = pd.merge(gender_age_train,phone_conv, how='outer', left_on='device_id', right_on='device_id')
device_merge.head()

device_id gender   age age_group  brand      model converted_brand
0 -8076087639492063270      M  35.0    M32-38     小米       MI 2          Millet
1 -2897161552818060146      M  35.0    M32-38     小米       MI 2          Millet
2 -8260683887967679142      M  35.0    M32-38     小米       MI 2          Millet
3 -4938849341048082022      M  30.0    M29-31     三星  Galaxy S4         Samsung
4   245133531816851882      M  30.0    M29-31  SUGAR       时尚手机           SUGAR

In [0]:
device_merge.shape

(87754, 7)

In [0]:
device_merge.count()

device_id          87754
gender             74645
age                74645
age_group          74645
brand              87726
model              87726
converted_brand    87726
dtype: int64

In [0]:
pd.crosstab(events['state'],events['city'] )

city                      Abohar  Achalpur  ...  Yelahanka  Yemmiganur
state                                       ...                       
AndamanandNicobarIslands       0         0  ...          0           0
AndhraPradesh                  0         0  ...          0        1180
ArunachalPradesh               0         0  ...          0           0
Assam                          0         0  ...          0           0
Bihar                          0         0  ...          0           0
Chandigarh                     0         0  ...          0           0
Chhattisgarh                   0         0  ...          0           0
Delhi                          0         0  ...          0           0
Goa                            0         0  ...          0           0
Gujarat                        0         0  ...          0           0
Haryana                        0         0  ...          0           0
HimachalPradesh                0         0  ...          0           0
JammuandKashmir                0         0  ...          0           0
Jharkhand                      0         0  ...          0           0
Karnataka                      0         0  ...        338           0
Kerala                         0         0  ...          0           0
MadhyaPradesh                  0         0  ...          0           0
Maharashtra                    0       630  ...          0           0
Manipur                        0         0  ...          0           0
Meghalaya                      0         0  ...          0           0
Mizoram                        0         0  ...          0           0
Nagaland                       0         0  ...          0           0
Orissa                         0         0  ...          0           0
Pondicherry                    0         0  ...          0           0
Punjab                       869         0  ...          0           0
Rajasthan                      0         0  ...          0           0
TamilNadu                      0         0  ...          0           0
Telangana                      0         0  ...          0           0
Tripura                        0         0  ...          0           0
UttarPradesh                   0         0  ...          0           0
Uttaranchal                    0         0  ...          0           0
WestBengal                     0         0  ...          0           0

[32 rows x 933 columns]

In [0]:
events.groupby(['state','city'])['city'].count()

state                     city            
AndamanandNicobarIslands  PortBlair           1515
AndhraPradesh             Adilabad            1010
                          Adoni                930
                          Alwal                704
                          Anakapalle           627
                                              ... 
WestBengal                Siuri                433
                          SouthDumDum         1072
                          Titagarh            1207
                          Ulubaria             877
                          UttarparaKotrung     749
Name: city, Length: 943, dtype: int64

In [0]:
events.query('state in ["MadhyaPradesh","Chhattisgarh", "Uttaranchal", "JammuandKashmir","Goa", "Nagaland"]')

event_id     device_id  ...       city          state
2197849    10117.0 -5.323073e+18  ...     Indore  MadhyaPradesh
2197850   112369.0 -5.323073e+18  ...     Indore  MadhyaPradesh
2197851   139098.0 -5.323073e+18  ...     Indore  MadhyaPradesh
2197852   190983.0 -5.323073e+18  ...     Indore  MadhyaPradesh
2197853   249507.0 -5.323073e+18  ...     Indore  MadhyaPradesh
...            ...           ...  ...        ...            ...
2458992  3218198.0  8.277000e+18  ...      Sarni  MadhyaPradesh
2458993  3241226.0 -4.634263e+18  ...    Khandwa  MadhyaPradesh
2458994  3246861.0  3.633748e+18  ...     Kohima       Nagaland
2458995  3247285.0  2.609354e+18  ...  BinaEtawa  MadhyaPradesh
2458996  3248948.0 -8.474949e+18  ...   Mandsaur  MadhyaPradesh

[261097 rows x 7 columns]

In [0]:
df_event = events.query('state in ["MadhyaPradesh","Chhattisgarh", "Uttaranchal", "JammuandKashmir","Goa", "Nagaland"]')
df_event.head()

event_id     device_id  ...    city          state
2197849   10117.0 -5.323073e+18  ...  Indore  MadhyaPradesh
2197850  112369.0 -5.323073e+18  ...  Indore  MadhyaPradesh
2197851  139098.0 -5.323073e+18  ...  Indore  MadhyaPradesh
2197852  190983.0 -5.323073e+18  ...  Indore  MadhyaPradesh
2197853  249507.0 -5.323073e+18  ...  Indore  MadhyaPradesh

[5 rows x 7 columns]

In [0]:
pd.crosstab(df_event['state'],df_event['city'] )

city             Ambikapur  Anantnag  Ashoknagar  ...  Ujjain  Vidisha  Wokha
state                                             ...                        
Chhattisgarh           539         0           0  ...       0        0      0
Goa                      0         0           0  ...       0        0      0
JammuandKashmir          0      1103           0  ...       0        0      0
MadhyaPradesh            0         0        1145  ...     480      873      0
Nagaland                 0         0           0  ...       0        0   1100
Uttaranchal              0         0           0  ...       0        0      0

[6 rows x 85 columns]

In [197]:
plt.figure(figsize = (15, 6))
df_event.groupby('state')['city'].count().sort_values(ascending=False).plot(kind='bar', color='g')
plt.ylabel('Count')

NameError: ignored

In [0]:
df_event.groupby(['city','state'])['event_id'].count()

city        state          
Ambikapur   Chhattisgarh        539
Anantnag    JammuandKashmir    1103
Ashoknagar  MadhyaPradesh      1145
Balaghat    MadhyaPradesh       534
Baramula    JammuandKashmir     519
                               ... 
Tikamgarh   MadhyaPradesh      1268
Udhampur    JammuandKashmir     745
Ujjain      MadhyaPradesh       480
Vidisha     MadhyaPradesh       873
Wokha       Nagaland           1100
Name: event_id, Length: 85, dtype: int64

In [0]:
##missing data in events
total = event_age.isnull().sum().sort_values(ascending=False)
percent = (event_age.isnull().sum()/event_age.isnull().count()).sort_values(ascending=False)
missing_data_event_age = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data_event_age.head(20)
print(missing_data_event_age)

NameError: ignored

In [0]:
##missing data in events
total = df_event.isnull().sum().sort_values(ascending=False)
percent = (df_event.isnull().sum()/df_event.isnull().count()).sort_values(ascending=False)
missing_data_dfevents = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data_dfevents.head(20)
print(missing_data_dfevents)

           Total   Percent
device_id     51  0.000195
state          0  0.000000
city           0  0.000000
latitude       0  0.000000
longitude      0  0.000000
timestamp      0  0.000000
event_id       0  0.000000


In [0]:

gender_age_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74645 entries, 0 to 74644
Data columns (total 4 columns):
device_id    74645 non-null int64
gender       74645 non-null object
age          74645 non-null int64
age_group    74645 non-null object
dtypes: int64(2), object(2)
memory usage: 2.3+ MB


In [0]:
phone_brand.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87726 entries, 0 to 87725
Data columns (total 3 columns):
device_id    87726 non-null int64
brand        87726 non-null object
model        87726 non-null object
dtypes: int64(1), object(2)
memory usage: 2.0+ MB


In [0]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3252950 entries, 0 to 3252949
Data columns (total 7 columns):
event_id     float64
device_id    float64
timestamp    object
longitude    object
latitude     object
city         object
state        object
dtypes: float64(2), object(5)
memory usage: 173.7+ MB


In [0]:
df_event.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 261097 entries, 2197849 to 2458996
Data columns (total 7 columns):
event_id     261097 non-null float64
device_id    261046 non-null float64
timestamp    261097 non-null object
longitude    261097 non-null object
latitude     261097 non-null object
city         261097 non-null object
state        261097 non-null object
dtypes: float64(2), object(5)
memory usage: 15.9+ MB


In [0]:
device_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 87754 entries, 0 to 87753
Data columns (total 7 columns):
device_id          87754 non-null int64
gender             74645 non-null object
age                74645 non-null float64
age_group          74645 non-null object
brand              87726 non-null object
model              87726 non-null object
converted_brand    87726 non-null object
dtypes: float64(1), int64(1), object(5)
memory usage: 5.4+ MB


In [0]:
event_age = pd.merge(events,device_merge,how='inner', left_on='device_id', right_on='device_id')
event_age.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/merge.py:1089: UserWarning:

You are merging on int and float columns where the float values are not equal to their int representation



event_id     device_id            timestamp  ... brand  model converted_brand
0     492.0  2.973348e+18  2016-05-04 00:12:23  ...    优米  UIMI3    Quality rice
1   38049.0  2.973348e+18  2016-05-02 09:15:32  ...    优米  UIMI3    Quality rice
2   58908.0  2.973348e+18  2016-05-03 20:59:11  ...    优米  UIMI3    Quality rice
3   58957.0  2.973348e+18  2016-05-03 21:51:04  ...    优米  UIMI3    Quality rice
4   73519.0  2.973348e+18  2016-05-01 07:15:53  ...    优米  UIMI3    Quality rice

[5 rows x 13 columns]

In [0]:
final_set = pd.merge(device_merge, df_event,how='inner', left_on='device_id', right_on='device_id')
final_set.head()

device_id gender   age  ...   latitude    city          state
0  8765877367300380672      F  32.0  ...  22.802167  Indore  MadhyaPradesh
1  8765877367300380672      F  32.0  ...  22.802167  Indore  MadhyaPradesh
2  8765877367300380672      F  32.0  ...  22.802167  Indore  MadhyaPradesh
3  8765877367300380672      F  32.0  ...  22.802167  Indore  MadhyaPradesh
4  8765877367300380672      F  32.0  ...  22.802167  Indore  MadhyaPradesh

[5 rows x 13 columns]

In [0]:
final_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2824 entries, 0 to 2823
Data columns (total 13 columns):
device_id          2824 non-null int64
gender             2824 non-null object
age                2824 non-null float64
age_group          2824 non-null object
brand              2824 non-null object
model              2824 non-null object
converted_brand    2824 non-null object
event_id           2824 non-null float64
timestamp          2824 non-null object
longitude          2824 non-null object
latitude           2824 non-null object
city               2824 non-null object
state              2824 non-null object
dtypes: float64(2), int64(1), object(10)
memory usage: 308.9+ KB


In [0]:
all_set = pd.merge(device_merge, events,how='inner', left_on='device_id', right_on='device_id')
all_set.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/merge.py:1100: UserWarning:

You are merging on int and float columns where the float values are not equal to their int representation



device_id gender   age  ...   latitude           city          state
0 -6552729385743211      M  28.0  ...  17.338947  Rajendranagar  AndhraPradesh
1 -6552729385743211      M  28.0  ...  17.338947  Rajendranagar  AndhraPradesh
2 -6552729385743211      M  28.0  ...  17.338947  Rajendranagar  AndhraPradesh
3 -6552729385743211      M  28.0  ...  17.338947  Rajendranagar  AndhraPradesh
4 -6552729385743211      M  28.0  ...  17.338947  Rajendranagar  AndhraPradesh

[5 rows x 13 columns]

In [0]:
all_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14290 entries, 0 to 14289
Data columns (total 13 columns):
device_id          14290 non-null int64
gender             14290 non-null object
age                14290 non-null float64
age_group          14290 non-null object
brand              14290 non-null object
model              14290 non-null object
converted_brand    14290 non-null object
event_id           14290 non-null float64
timestamp          14290 non-null object
longitude          14290 non-null object
latitude           14290 non-null object
city               14290 non-null object
state              14290 non-null object
dtypes: float64(2), int64(1), object(10)
memory usage: 1.5+ MB


In [0]:
##all_set.groupby('state')['event_id'].count().sort_values(ascending=False)
event_age.groupby('state')['event_id'].count().sort_values(ascending=False)
##,'city','brand','mode'

state
Maharashtra         2835
MadhyaPradesh       2633
TamilNadu           2566
Delhi               1841
WestBengal           879
Rajasthan            796
AndhraPradesh        669
Karnataka            444
UttarPradesh         363
Bihar                281
Haryana              278
Gujarat              129
ArunachalPradesh     110
Telangana            102
JammuandKashmir       78
Kerala                57
Nagaland              56
Chhattisgarh          50
Jharkhand             45
Punjab                32
Orissa                23
Assam                  9
Goa                    7
Tripura                4
Chandigarh             3
Name: event_id, dtype: int64

In [0]:
event_age.shape

(14290, 13)

In [0]:
event_age.groupby('state')['event_id'].count().sort_values(ascending=False).plot(kind='bar',figsize=(10,12))

In [0]:
event_age.groupby(['state','city'])['event_id'].count().sort_values(ascending=False).plot(kind='bar',figsize=(10,12))

In [0]:
d= event_age.groupby(['state','city','device_id'])


In [0]:
event_age.groupby(['state','city'])['device_id'].count()

state          city      
AndhraPradesh  Adilabad       6
               Alwal         74
               Anakapalle     1
               Anantapur      6
               Belampalli    56
                             ..
WestBengal     Kharagpur     43
               Naihati        2
               Pujali         6
               Shiliguri      1
               Ulubaria       2
Name: device_id, Length: 168, dtype: int64

In [0]:
event_age.groupby('state')['device_id'].value_counts().sort_values(ascending=False).plot(kind='bar',figsize=(10,12))

In [0]:
data = [go.Scattergeo(lon=event_age.iloc[event_age['event_id'].sort_values(ascending=False)[:10].index, :]['longitude'], 
                      lat=event_age.iloc[event_age['event_id'].sort_values(ascending=False)[:10].index, :]['latitude'], 
                      text=event_age.iloc[event_age['event_id'].sort_values(ascending=False)[:10].index, :][['state', 'event_id']], 
                      name='',
                      marker=dict(size=event_age.iloc[event_age['event_id'].sort_values(ascending=False)[:10].index, :]['event_id'].count(), 
                                  color='Green'))]


In [0]:
data

[Scattergeo({
     'lat': array(['10.996744', '26.959949', '13.168106', '28.685333', '19.019585',
                   '28.702655', '28.714736', '28.714736', '9.551846', '27.46417'],
                  dtype=object),
     'lon': array(['76.997629', '75.899023', '80.360389', '77.229586', '72.840445',
                   '77.297436', '77.291058', '77.291058', '78.14106', '82.215267'],
                  dtype=object),
     'marker': {'color': 'Green', 'size': 10},
     'name': '',
     'text': array([['TamilNadu', 3251690.0],
                    ['Rajasthan', 3251524.0],
                    ['TamilNadu', 3251517.0],
                    ['Delhi', 3251170.0],
                    ['Maharashtra', 3250685.0],
                    ['Delhi', 3250600.0],
                    ['Delhi', 3250526.0],
                    ['Delhi', 3250376.0],
                    ['TamilNadu', 3250285.0],
                    ['UttarPradesh', 3250098.0]], dtype=object)
 })]

In [0]:
layout = go.Layout(title=go.layout.Title(text='State wise plot'), 
                   showlegend=False,
                   geo=dict(scope='usa', projection=go.layout.geo.Projection(type='albers usa'), showlakes=True,
                            lakecolor='rgb(255, 255, 255)'))

In [0]:
fig = go.Figure(data=data, layout=layout)

In [0]:
fig.show()

In [0]:
iplot(fig)

In [0]:
import plotly

In [0]:
from plotly.graph_objs import Scatter, Layout

In [0]:
plotly.offline.init_notebook_mode(connected=True)

Observations:
  1. Gender_age_train

     1.1 NULL values not found. Total Records 74645 
     1.2 Age Groups defined are based on Gender and Age. Total 12 age groups (6 + 6)
     1.3 Age Group range for male and female is defined separalty 
     1.4 Male users are more than Female Users (Overall)  
     1.5  
  2. Phone brand

     2.1 NULL values not found. Total records 87726

     2.2 Distinct Models are 1467

     2.3 Distinct Brands are 116

  3. Events

     3.1 Total Records  3252950

     3.2 Few Values found missing. Device_id = 453, Latitude = 423,Longitude=42,         state 377
     3.3 Total State =  32 & Total City = 933

     3.4  Total number of records to analyse as per assigned states are 261097 

     3.5  For our study total 6 states are given and Madhyapradesh has maximum count of cities. Total Cities to study 85

     3.6 After getting data for 6 states under our study we observed that 51 records doesnot have device id.

     3.7 Top 10 states where maximum event recorded
state
Delhi                       751733
Maharashtra                 677105
TamilNadu                   436282
AndhraPradesh               321332
MadhyaPradesh               232690
Rajasthan                   196361
WestBengal                  196161
Karnataka                    99058
UttarPradesh                 94750
Gujarat                      42881

3.8 Minimum event recorded 

Nagaland                      2298

Pondicherry                   1741

Mizoram                       1613

AndamanandNicobarIslands      1515

Meghalaya                     1515

HimachalPradesh               1409

Manipur                        989

Chandigarh                     894

Tripura                        892

ArunachalPradesh               608


3.9  Maximum and minimum events recorded city wise (Top 5 and Bottom 5 )

state          city            
Delhi          Delhi               744212
TamilNadu      Chennai             366828
Maharashtra    Pune                317213
               Mumbai              285246
AndhraPradesh  Visakhapatnam       235725
                                    ...  
               Ramachandrapuram       279
Punjab         Sirhind                269
AndhraPradesh  Tadepallegudem         264
Orissa         Brajrajnagar           263
TamilNadu      Kovilpatti             258

  4. Gender_age_train + Phone_brand

      4.1 Total matching records found 74617
         
5.  All table merge with Device_id
   5.1  Maximum event count in Maharashtra 2835 and Minimum event count in Chandigarh 3.
   5.2 Top 10 states where maximum event recorded

	state

Maharashtra         2835

MadhyaPradesh       2633

TamilNadu           2566

Delhi               1841

WestBengal           879

Rajasthan            796

AndhraPradesh        669

Karnataka            444

UttarPradesh         363

Bihar                281


5.3    City wise maximum and minimum  (TOP 5 and Bottom 5 Cities with states)

State          city       

MadhyaPradesh  Indore         2366

Maharashtra    Mumbai         2160

TamilNadu      Chennai        2004

Delhi          Delhi          1841

WestBengal     Calcutta        713

Chhattisgarh   Korba             1
                Chirmiri          1
               

Karnataka      Hospet            1

TamilNadu      Thuthukkudi       1

Rajasthan      Baran             1 
